bank/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('create/', views.create_account, name='create'),
    path('list/', views.account_list, name='account_list'),
    path('detail/<int:account_id>/', views.account_detail, name='account_detail'),
    path('detail/<int:account_id>/edit/', views.edit_account, name='edit_account'),
    path('card/create/<int:account_id>', views.card_create, name='card_create'),
    path('card/list/', views.card_list, name='card_list'),
    path('card/detail/<int:card_id>/', views.card_detail, name='card_detail'),
    path('card/detail/<int:card_id>/edit', views.edit_card, name='edit_card'),
    path('status/<int:card_id>', views.change_status_card, name='status'),
    path(
        'delete/confirmation/<int:account_id>/',
        views.delete_account_confirmation,
        name='delete_confirmation',
    ),
    path('delete/account/<int:account_id>/', views.delete_account, name='delete_account'),
    path('create/account/', views.create_account_confirmation, name='create_account_confirmation'),
    path('card/request/', views.card_request, name='card_request'),
    path(
        'create/card/<int:account_id>/',
        views.create_card_confirmation,
        name='create_card_confirmation',
    ),
    path(
        'delete/confirmation/<int:card_id>',
        views.delete_card_confirmation,
        name='delete_card_confirmation',
    ),
    path('delete/card/<int:card_id>/', views.delete_card, name='delete_card'),
    path('transactions/', views.transaction_list, name='transaction_list'),
]

bank/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'api'

router = routers.DefaultRouter()
router.register('accounts', views.AccountViewSet, basename='accounts')
router.register('cards', views.CardViewSet, basename='cards')
router.register('transactions', views.TransactionViewSet, basename='transactions')


urlpatterns = [
    path('', include(router.urls)),
]

bank/bank/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from transaction import views

urlpatterns = [
    path('api/', include('api.urls', namespace='api')),
    path('payment/', views.payment, name='payment'),
    path('transfer/incoming/', views.transfer_incoming, name='transfer_incoming'),
]

urlpatterns += i18n_patterns(
    path('', include('client.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('transfer/', include('transaction.urls', namespace='transfer')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('rosetta/', include('rosetta.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bank/transaction/urls.py
from django.urls import path

from . import views

app_name = 'adabank'

urlpatterns = [
    path(
        'outcoming/<int:account_id>',
        views.transfer_outcoming,
        name='transfer_outcoming',
    ),
    path(
        'pdf/<int:transaction_id>',
        views.transaction_pdf,
        name='transaction_pdf',
    ),
    path(
        'outcoming_done/<int:transaction_id>',
        views.outcoming_done,
        name='outcoming_done',
    ),
    path('csv/<str:account_id>/', views.transactions_to_csv, name='transaction_to_csv'),
]

bank/transaction/models.py
from account.models import Account, Card
from django.db import models
from django.utils.translation import gettext_lazy as _


class Transaction(models.Model):
    class Type(models.TextChoices):
        PAYMENT = 'PAY', _('Payment')
        INCOMING = 'INC', _('Incoming')
        OUTCOMING = 'OUT', _('Outcoming')

    agent = models.CharField(_('agent'), max_length=200)
    concept = models.CharField(_('concept'), max_length=50)
    timestamp = models.DateTimeField(_('timestamp'), auto_now_add=True)
    amount = models.DecimalField(_('amount'), max_digits=10, decimal_places=2)
    kind = models.CharField(_('kind'), max_length=3, choices=Type.choices)
    account = models.ForeignKey(Account, related_name='transactions', on_delete=models.CASCADE)
    card = models.ForeignKey(
        Card,
        related_name='transactions',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    commission = models.DecimalField(_('comission'), max_digits=10, decimal_places=2)
    balance = models.DecimalField(_('balance'), max_digits=10, decimal_places=2)

    class Meta:
        ordering = ['-timestamp']
        indexes = [
            models.Index(fields=['-timestamp']),
        ]

    def __str__(self):
        return f'{self.kind}, {self.agent}, {self.concept}'


class Commission(models.Model):
    kind = models.CharField(_('kind'), max_length=3, choices=Transaction.Type.choices)
    range1 = models.DecimalField(_('range 1'), max_digits=5, decimal_places=2)
    range2 = models.DecimalField(_('range 2'), max_digits=5, decimal_places=2)
    range3 = models.DecimalField(_('range 3'), max_digits=5, decimal_places=2)


class WhitelistedBank(models.Model):
    name = models.CharField(_('name'), max_length=20)
    url = models.CharField(max_length=250)
    code = models.CharField(_('code'), max_length=2)

bank/transaction/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class transferOutcomingForm(forms.Form):
    cac = forms.CharField(label=_('cac'))
    concept = forms.CharField(label=_('concept'))
    amount = forms.DecimalField(label=_('amount'))

bank/transaction/views.py
import csv
import io
import json

import requests

# from weasyprint import HTML, CSS ERROR!!!!
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.http import HttpRequest, HttpResponse, HttpResponseBadRequest, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import get_template
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from xhtml2pdf import pisa

from account.models import Account, Card, Status

from .forms import transferOutcomingForm
from .models import Transaction, WhitelistedBank
from .utils import calc_commission


@require_POST
@csrf_exempt
def payment(request: HttpRequest):
    data = json.loads(request.body)
    commission = calc_commission(Transaction.Type.PAYMENT.value, data['amount'])
    try:
        card = Card.objects.get(code=data['ccc'])
        account_balance = float(card.account.balance)
    except Card.DoesNotExist:
        return HttpResponseBadRequest(f'The card with code {data["ccc"]} does not exist')
    if not check_password(data['pin'], card.pin):
        return HttpResponseForbidden("The pin doesn't code")
    if float(data['amount']) + commission > account_balance:
        return HttpResponseBadRequest('Not enough money on account')
    if card.account.status != Status.ACTIVE:
        return HttpResponseBadRequest('Unable to use account')
    if card.status != Status.ACTIVE:
        return HttpResponseBadRequest('Unable to use card')
    concept = f'Card payment to {data["business"]}'
    card.account.balance = account_balance - (float(data['amount']) + commission)
    card.account.save()
    Transaction.objects.create(
        agent=data['business'],
        concept=concept,
        amount=data['amount'],
        kind=Transaction.Type.PAYMENT,
        card=card,
        account=card.account,
        commission=commission,
        balance=card.account.balance,
    )
    return HttpResponse()


@require_POST
@csrf_exempt
def transfer_incoming(request: HttpRequest):
    data = json.loads(request.body)
    try:
        account = Account.objects.get(code=data['cac'])
        account_balance = float(account.balance)
    except Account.DoesNotExist:
        return HttpResponseForbidden("The account doesn't code or not exist")
    if account.status != Status.ACTIVE:
        return HttpResponseBadRequest('Unable to use account')
    concept = f'Transfer received in respect of {data["concept"]}'
    commission = calc_commission(Transaction.Type.INCOMING.value, data['amount'])
    account.balance = account_balance + (float(data['amount']) - commission)
    account.save()
    Transaction.objects.create(
        agent=data['sender'],
        concept=concept,
        amount=data['amount'],
        kind=Transaction.Type.INCOMING,
        account=account,
        commission=commission,
        balance=account.balance,
    )
    return HttpResponse()


@login_required
@csrf_exempt
def transfer_outcoming(request: HttpRequest, account_id: int):
    """
    For the request to other banks, function gets the id
    and get from database the url of bank with that id.
    Example: A5-0002 -> Will get from database bank url with id=5

    Try - Except are implemented to check if the bank with the requested id
    exists in database and to check if the other bank url is working
    correctly (If other bank is not deployed o have any problem with server,
    an error will be showed)
    """
    form = transferOutcomingForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            cd = form.cleaned_data
            sender_account = Account.objects.get(id=account_id)
            if sender_account.status != Status.ACTIVE:
                messages.error(
                    request,
                    _("Yo can't make transactios with this account because it's not active"),
                )
                return render(request, 'transaction/outcoming.html', dict(form=form))
            commission = calc_commission(Transaction.Type.OUTCOMING.value, cd['amount'])
            account_balance = float(sender_account.balance)
            if account_balance < float(cd['amount']) + commission:
                messages.error(request, _('Not enough money in account!'))
                return render(request, 'transaction/outcoming.html', dict(form=form))
            data = {
                'sender': sender_account.code,
                'cac': cd['cac'],
                'concept': cd['concept'],
                'amount': str(cd['amount']),
            }
            code = cd['cac'][1]
            # Check bank existence on database with the id extracted from 'cac' field
            try:
                bank_url = WhitelistedBank.objects.get(id=code).url
            except:
                messages.error(request, _('The CAC %(cac)s is not valid') % {'cac': cd['cac']})
                return render(request, 'transaction/outcoming.html', dict(form=form))
            # Check that the url of the other bank it's working correcly
            try:
                r = requests.post(
                    bank_url,
                    json=data,
                )
            except requests.exceptions.ConnectionError:
                messages.error(
                    request,
                    _('The bank to which you are trying to make a transfer is not available.'),
                )
                return render(request, 'transaction/outcoming.html', dict(form=form))
            if r.status_code != 200:
                print(r.reason)
                messages.error(request, _('The data are not valid'))
                return render(request, 'transaction/outcoming.html', dict(form=form))
            sender_account.balance = account_balance - (float(cd['amount']) + commission)
            sender_account.save()
            new_transaction = Transaction.objects.create(
                agent=sender_account.code,
                concept=cd['concept'],
                amount=cd['amount'],
                kind=Transaction.Type.OUTCOMING,
                account=sender_account,
                commission=commission,
                balance=sender_account.balance,
            )
            return redirect('adabank:outcoming_done', transaction_id=new_transaction.pk)
        else:
            messages.error(request, _('The data are not valid'))
    return render(request, 'transaction/outcoming.html', dict(form=form))


def outcoming_done(request, transaction_id):
    transaction = get_object_or_404(Transaction, id=transaction_id)
    return render(request, 'transaction/outcoming_done.html', {'transaction': transaction})


def transaction_pdf(request, transaction_id):
    transaction = get_object_or_404(Transaction, id=transaction_id)
    template = get_template('transaction/pdf.html')
    context = {'transaction': transaction}
    html_content = template.render(context)
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=transaction_{transaction_id}.pdf'
    buffer = io.BytesIO()
    pisa.CreatePDF(html_content, dest=buffer)
    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response


@login_required
def transactions_to_csv(request, account_id: int = None) -> HttpResponse:
    """
    Transaction kind is checked to add "-" or "+" to the amout so user can
    quick view if the transactions involve a an addition or subtraction of money
    """
    transactions = Transaction.objects.filter(account__id=account_id)
    account = Account.objects.get(id=account_id)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment;filename={account.code}_transactions.csv'
    writer = csv.writer(response)
    headers = [field.name for field in Transaction._meta.get_fields()]
    writer.writerow(headers)
    for transaction in transactions:
        data = []
        for header in headers:
            if (transaction.kind == 'PAY' or transaction.kind == 'OUT') and header == 'amount':
                data.append(f'-{transaction.amount}')
                continue
            elif transaction.kind == 'INC' and header == 'amount':
                data.append(f'+{transaction.amount}')
                continue
            data.append(getattr(transaction, header))
        writer.writerow(data)
    return response

bank/transaction/templates/transaction/outcoming.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} {% trans "Transfer" %} | Adabank{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-4 col-sm-2 col-xs-1 sidebar2">
      {% include "sidebar.html" %}
    </div>
    <div class="col-md-8 col-sm-10 col-xs-10 mt-2 card-list">
      {% if messages %}
      <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
      </ul>
      {% endif %}
        <h1 class="title-card-list">{% trans "Make an outcoming transaction" %}</h1>
        <form method="post">
            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th>{% trans "CAC" %}</th>
                        <th>{% trans "Concept" %}</th>
                        <th>{% trans "Amount" %}</th>
                    </tr>
                    <tr>
                      <td>{{ form.cac }}</td>
                      <td>{{ form.concept }}</td>
                      <td>{{ form.amount }}</td>
                    </tr>
              </table>
              {% csrf_token %}
              <input type="submit" value="{% trans "Send" %}">
            </form>
            </div>  
    </div>
</div>
{% endblock %}

bank/transaction/templates/transaction/outcoming_done.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{% trans "Done Outcoming | Adabank" %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-4 col-sm-2 col-xs-1 sidebar2">
      {% include "sidebar.html" %}
    </div>
    <div class="col-md-8 col-sm-10 col-xs-10 mt-2 card-list">
        <h1 class="title-card-list">{% trans "Outcoming transaction" %} {{ transaction.id }} {% trans "done successfully" %}</h1>
        <table class="transaction-table">
          <tr style="background-color: #f2f2f2;">
            <th>{% trans "Transaction Code" %}</th>
            <td> {{ transaction.id }}</td>
          </tr>
          <tr>
              <th>{% trans "Account" %}</th>
              <td>{{ transaction.account }}</td>
          </tr>
          <tr style="background-color: #f2f2f2;">
              <th>{% trans "Agent" %}</th>
              <td>{{ transaction.agent }}</td>
          </tr>
          <tr>
              <th>{% trans "Concept" %}</th>
              <td>{{ transaction.concept }}</td>
          </tr>
          <tr style="background-color: #f2f2f2;">
              <th>{% trans "Timestamp" %}</th>
              <td>{{ transaction.timestamp }}</td>
          </tr>
          <tr>
              <th>{% trans "Amount" %}</th>
              <td>{{ transaction.amount }} €</td>
          </tr>
          <tr style="background-color: #f2f2f2;">
              <th>{% trans "Commission" %}</th>
              <td>{{ transaction.commission }} €</td>
          </tr>
          <tr>
              <th>{% trans "Transfer Type" %}</th>
              <td>{{ transaction.kind }}</td>
          </tr>
        </table>
        <p><a href="{% url 'adabank:transaction_pdf' transaction.id %}">{% trans "Generate PDF" %}</a></p>
        <p><a href="{% url "account:account_list" %}">{% trans "Back to my accounts" %}</a></p>
      </div> 
</div>
{% endblock %}

bank/transaction/templates/transaction/pdf.html
{% load i18n %}
<html>
<head>
    <style>
        body {
            font-family: sans-serif;
            margin: 20px;
            text-align: center;
        }
        #container {
            display: inline-block;
            text-align: left;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            
        }
        th, td {
            align-items: center;
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 20px;
        }
    </style>
</head>
<body>
    <div id="container">
        <h1 style="text-align:center;font-size:25px">AdaBank</h1>
        <table>
            <tr style="background-color: #f2f2f2;">
                <th>{% trans "Transaction Code" %}</th>
                <td>{{ transaction.id }}</td>
            </tr>
            <tr>
                <th>{% trans "Account" %}</th>
                <td>{{ transaction.account }}</td>
            </tr>
            <tr style="background-color: #f2f2f2;">
                <th>{% trans "Agent" %}</th>
                <td>{{ transaction.agent }}</td>
            </tr>
            <tr>
                <th>{% trans "Concept" %}</th>
                <td>{{ transaction.concept }}</td>
            </tr>
            <tr style="background-color: #f2f2f2;">
                <th>{% trans "Timestamp" %}</th>
                <td>{{ transaction.timestamp }}</td>
            </tr>
            <tr>
                <th>{% trans "Amount" %}</th>
                <td>{{ transaction.amount }} €</td>
            </tr>
            <tr style="background-color: #f2f2f2;">
                <th>{% trans "Commission" %}</th>
                <td>{{ transaction.commission }} €</td>
            </tr>
            <tr>
                <th>{% trans "Transfer Type" %}</th>
                <td>{{ transaction.kind }}</td>
            </tr>
        </table>
        <p style="font-size:15px;text-align:center;margin-top:40px;">{% trans "Thank you for using AdaBank!" %}</p>
    </div>
</body>
</html>