bank/account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('create/', views.create_account, name='create'),
    path('list/', views.account_list, name='account_list'),
    path('detail/<int:account_id>/', views.account_detail, name='account_detail'),
    path('detail/<int:account_id>/edit/', views.edit_account, name='edit_account'),
    path('card/create/<int:account_id>', views.card_create, name='card_create'),
    path('card/list/', views.card_list, name='card_list'),
    path('card/detail/<int:card_id>/', views.card_detail, name='card_detail'),
    path('card/detail/<int:card_id>/edit', views.edit_card, name='edit_card'),
    path('status/<int:card_id>', views.change_status_card, name='status'),
    path(
        'delete/confirmation/<int:account_id>/',
        views.delete_account_confirmation,
        name='delete_confirmation',
    ),
    path('delete/account/<int:account_id>/', views.delete_account, name='delete_account'),
    path('create/account/', views.create_account_confirmation, name='create_account_confirmation'),
    path('card/request/', views.card_request, name='card_request'),
    path(
        'create/card/<int:account_id>/',
        views.create_card_confirmation,
        name='create_card_confirmation',
    ),
    path(
        'delete/confirmation/<int:card_id>',
        views.delete_card_confirmation,
        name='delete_card_confirmation',
    ),
    path('delete/card/<int:card_id>/', views.delete_card, name='delete_card'),
    path('transactions/', views.transaction_list, name='transaction_list'),
]

bank/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'api'

router = routers.DefaultRouter()
router.register('accounts', views.AccountViewSet, basename='accounts')
router.register('cards', views.CardViewSet, basename='cards')
router.register('transactions', views.TransactionViewSet, basename='transactions')


urlpatterns = [
    path('', include(router.urls)),
]

bank/bank/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from transaction import views

urlpatterns = [
    path('api/', include('api.urls', namespace='api')),
    path('payment/', views.payment, name='payment'),
    path('transfer/incoming/', views.transfer_incoming, name='transfer_incoming'),
]

urlpatterns += i18n_patterns(
    path('', include('client.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('transfer/', include('transaction.urls', namespace='transfer')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('rosetta/', include('rosetta.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bank/client/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('test/pdf/', views.download_pdf, name='pdf'),
]

bank/client/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _


class Profile(models.Model):
    identification = models.CharField(_('identification'), max_length=9, unique=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_birth = models.DateField(
        _('date of birth'),
    )
    avatar = models.ImageField(_('avatar'), upload_to='users/%Y/%m/%d/', blank=True)

    def __str__(self) -> str:
        return f'Profile of {self.user.username}'

bank/client/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from .models import Profile


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(
        label='', widget=forms.PasswordInput(attrs={'placeholder': _('Password')})
    )
    password2 = forms.CharField(
        label='', widget=forms.PasswordInput(attrs={'placeholder': _('Re-type Password')})
    )
    username = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'placeholder': _('Username')}),
        help_text='',
    )
    first_name = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'placeholder': _('First Name')}),
        help_text='',
    )
    last_name = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'placeholder': _('Last Name')}),
        help_text='',
    )
    email = forms.EmailField(
        label='', widget=forms.EmailInput(attrs={'placeholder': _('Email')}), help_text=''
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError(_("Passwords don't match."))
        return cd['password2']


class ProfileRegistrationForm(forms.ModelForm):
    date_of_birth = forms.DateField(label='', widget=forms.TextInput(attrs={'type': 'date'}))
    identification = forms.CharField(
        label='', widget=forms.TextInput(attrs={'placeholder': _('Identification')})
    )

    class Meta:
        model = Profile
        fields = ['identification']


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['date_of_birth', 'avatar']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class EmailForm(forms.ModelForm):
    email = forms.EmailField(
        label='', widget=forms.EmailInput(attrs={'placeholder': _('Email')}), help_text=''
    )

    class Meta:
        model = User
        fields = ['email']

bank/client/views.py
import weasyprint
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _

from account.models import Account, Card
from account.utils import cvv_generator, expiry_generator, pin_generator

from .forms import ProfileEditForm, ProfileRegistrationForm, UserEditForm, UserRegistrationForm
from .models import Profile


def index(request: HttpRequest) -> HttpResponse:
    return render(request, 'client/index.html')


def register(request: HttpRequest) -> HttpResponse:
    """
    When a user is registered, an account and a card is automatically generated
    for the new user. The registration also involves the creation of a profile
    to extend the base Djano's user
    """
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = ProfileRegistrationForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            new_user = user_form.save(commit=False)
            # Not saving the user on DB to encrypt password
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(
                user=new_user,
                date_of_birth=profile_form.cleaned_data['date_of_birth'],
                identification=profile_form.cleaned_data['identification'],
            )
            new_account = Account.objects.create(client=new_user)
            new_account.code = f'A4-{new_account.id:04d}'
            new_account.save()
            pin = pin_generator()
            new_card = Card(account=new_account, expiry=expiry_generator(), cvv=cvv_generator())
            new_card.pin = make_password(pin)
            new_card.save()
            new_card.code = f'C4-{new_card.id:04d}'
            new_card.save()
            subject = _('Pin for your new card of account %(account_code)s') % {
                'account_code': new_account.code
            }
            message = _(
                'Dear new client\nThis is your PIN for the new requested card: %(card)s\nNEVER FORGET IT, IT WILL ONLY BE SHOWN NOW'
            ) % {'user': request.user.username, 'card': pin}
            send_mail(subject, message, 'adalovelacebank@gmail.com', [new_user.email])
            return redirect('login')
    else:
        user_form = UserRegistrationForm()
        profile_form = ProfileRegistrationForm()
    return render(
        request,
        'client/register.html',
        {'user_form': user_form, 'profile_form': profile_form},
    )


@login_required
def edit(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile, data=request.POST, files=request.FILES
        )
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, _('Changes done'))
            return redirect('profile')
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    return render(
        request,
        'client/edit.html',
        {'user_form': user_form, 'profile_form': profile_form},
    )


@login_required
def profile(request: HttpRequest) -> HttpResponse:
    profile = Profile.objects.get(user=request.user)
    return render(request, 'client/profile.html', dict(profile=profile, section='profile'))


@login_required
def download_pdf(request):
    html = render_to_string('test/pdf/test.html')
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=test.pdf'
    weasyprint.HTML(string=html).write_pdf(
        response, stylesheets=[weasyprint.CSS(settings.STATIC_ROOT / 'css/test.css')]
    )
    return response

bank/client/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title %} {% endblock %}</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
  <link rel="icon" href="{% static 'img/adabank_favicon.png' %}" type="image/x-icon" />
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
</head>

<body>
  {% block content %} {% endblock %}
  <script src="{% static 'js/timer.js' %}"></script>
</body>

</html>

bank/client/templates/header.html
{% load static %}
{% load i18n %}
{% load bootstrap3 %}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand logo" href="{% url 'index' %}">AdaBank</a>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav navbar-left">
        </ul>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li><a {% if section == 'accounts' %} class="selected" {% endif %} href="{% url 'account:account_list' %}">{% trans "Accounts" %}</a></li>
          <li><a {% if section == 'cards' %} class="selected" {% endif %} href="{% url 'account:card_list' %}">{% trans "Cards" %}</a></li>
          <li><a {% if section == 'transactions' %} class="selected" {% endif %} href="{% url 'account:transaction_list' %}">{% trans "Transactions" %}</a></li>
          <li><a {% if section == 'profile' %} class="selected" {% endif %} href="{% url 'profile' %}">{% trans "Profile" %}</a></li>
          <li><a href="#" class="logoutlink" onclick=alertando()>{% trans "Logout" %}</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">{% trans "Sign in" %}</a></li>
            <li ><a href="{% url 'register' %}">{% trans "Sign up" %}</span></a></li>
          {% endif %}
          <li>
            {% if request.LANGUAGE_CODE == 'es' %} <a href="/en{{ request.path|slice:"3:" }}">🇬🇧 English</a>
            {% elif request.LANGUAGE_CODE == 'en' %} <a href="/es{{ request.path|slice:"3:" }}">🇪🇸 Español</a>
            {% endif %}  
        </li>
        </ul>
      </div>
    </div>
  </nav>
  <script>
    function alertando(){
      let main = '{% url "logout" %}'
      window.location.href = main
    }
  </script>

bank/client/templates/sidebar.html
{% load static %}
{% load i18n %}
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}" />
</head>
<body>
    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
            <div class="custom-menu">
                <button type="button" id="sidebarCollapse" class="btn btn-primary">
                    <i class="fa fa-bars"></i>
                </button>
            </div>
            <h1><a href="{% url 'index' %}" class="logo">Adabank</a></h1>
            <ul class="list-unstyled components mb-5">
                <li class="active">
                    <a href="{% url 'index' %}"><span class="fa fa-home mr-3"></span> {% trans "Home" %}</a>
                </li>
                <li>
                    <a {% if section == 'accounts' %} class="selected" {% endif %} href="{% url 'account:account_list' %}"><span class="fa fa-list-ul mr-3"></span> {% trans "Accounts" %}</a>
                </li>
                <li>
                    <a {% if section == 'cards' %} class="selected" {% endif %} href="{% url 'account:card_list' %}"><span class="fa fa-credit-card mr-3"></span> {% trans "Cards" %}</a>
                </li>
                <li>
                    <a href="{% url 'account:transaction_list' %}"><span class="fa fa-exchange mr-3"></span> {% trans "Transactions" %}</a>
                </li>
                <li>
                    <a {% if section == 'profile' %} class="selected" {% endif %} href="{% url 'profile' %}"><span class="fa fa-user mr-3"></span> {% trans "Profile" %}</a>
                </li>
                <li>
                    <a href="#" class="logoutlink" onclick=alertando()><span class="fa fa-sign-out mr-3"></span>{% trans "Logout" %}</a>
                </li>
                <li>
                    {% if request.LANGUAGE_CODE == 'es' %} <a href="/en{{ request.path|slice:"3:" }}">🇬🇧 English</a>
                    {% elif request.LANGUAGE_CODE == 'en' %} <a href="/es{{ request.path|slice:"3:" }}">🇪🇸 Español</a>
                    {% endif %}  
                </li>
            </ul>
        </nav>
    </div>
    <script src="{% static 'js/main.js' %}"></script>
    <script>
        function alertando() {
            let main = '{% url "logout" %}'
            window.location.href = main
        }
    </script>
</body>
</html>